version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: ../Dockerfile.backend.dev
    container_name: probyr-backend-dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=probyr_crm
      - DB_USER=postgres
      - DB_PASSWORD=password
    volumes:
      - ./backend/src:/app/src:ro              # Mount source code (read-only)
      - ./backend/package.json:/app/package.json:ro
      - ./backend/tsconfig.json:/app/tsconfig.json:ro
      - ./backend/migrations:/app/migrations:ro
      - backend_node_modules:/app/node_modules  # Named volume for node_modules
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - probyr-network
    
  frontend:
    build:
      context: ./frontend  
      dockerfile: ../Dockerfile.dev
    container_name: probyr-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000
    volumes:
      - ./frontend/src:/app/src:ro              # Mount source code (read-only)
      - ./frontend/public:/app/public:ro
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/vite.config.ts:/app/vite.config.ts:ro
      - ./frontend/tailwind.config.js:/app/tailwind.config.js:ro
      - ./frontend/tsconfig.json:/app/tsconfig.json:ro
      - ./frontend/index.html:/app/index.html:ro
      - frontend_node_modules:/app/node_modules  # Named volume for node_modules
    restart: unless-stopped
    networks:
      - probyr-network
    
  db:
    image: postgres:15-alpine
    container_name: probyr-db-dev
    environment:
      - POSTGRES_DB=probyr_crm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d probyr_crm"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - probyr-network

volumes:
  backend_node_modules:
  frontend_node_modules:
  postgres_dev_data:

networks:
  probyr-network:
    driver: bridge