version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: probyr-lite-crm
    ports:
      - "${PORT:-4000}:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=probyr_crm
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - probyr-network

  db:
    image: postgres:15-alpine
    container_name: probyr-db
    environment:
      - POSTGRES_DB=probyr_crm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d probyr_crm"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - probyr-network

volumes:
  postgres_data:

networks:
  probyr-network:
    driver: bridge