version: '3.8'

services:
  probyr-crm:
    build: .
    container_name: probyr-crm
    ports:
      - "8061:8061"
    environment:
      - NODE_ENV=production
      - PORT=8061
    volumes:
      - ./data:/app/data
      - crm_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8061/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - crm-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: probyr-crm-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - probyr-crm
    restart: unless-stopped
    networks:
      - crm-network
    profiles:
      - production

volumes:
  crm_data:
    driver: local

networks:
  crm-network:
    driver: bridge